title: Swiss Jekyll Theme
description: 'Product, Tech and more'
social_link: ''
social_username: ''
github_repo: mayurlean
github_username: mayurjobanputra
theme_color: white
remote_theme: internet-de-france/swiss
baseurl: /mayurlean
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
